name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,

  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: path/to/artifacts
